SDK_PATH = C:/Users/au091346/Desktop/c_sdk_220203/c_sdk_220203/MinGW

all:
	gcc -I./include -I$(SDK_PATH)/include src/main.c src/camera.c -L$(SDK_PATH)/lib -lmingw32 -lSDL2main -lSDL2 -lopengl32 -lm -o main.exe